name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: raven-actions/actionlint@v2

  schema:
    name: action schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pipx run check-jsonschema --builtin-schema vendor.github-actions ./*/action.yml
